apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deploy
  labels:
    app: devops-project-app
spec:
  selector:
    matchLabels:
      app: devops-project-app
  replicas: 2
  template:
    metadata:
      labels:
        app: devops-project-app
    spec:
      containers:
      - name: devops-project
        image: devops-project:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
